- name: Install the latest version of Ngnix 
  yum:
    name: nginx 
    state: latest
  tags:
    - frontend 

- name: Restart service httpd, in all cases
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes
- name: Download foo.conf
  get_url:
    url: http://example.com/path/file.conf
    dest: /etc/foo.conf
    mode: '0440'