- name: frontend 
  debug: 
     msg: This is Frontend

- name: frontend 
  debug: 
     msg: This is Frontend

- name: frontend 
  debug: 
     msg: This is Frontend

- name: frontend 
  debug: 
     msg: This is Frontend

- name: frontend 
  debug: 
     msg: This is Frontend