- name: Install the latest version of Ngnix 
  yum:
    name: nginx 
    state: latest
  tags:
    - frontend 

- name: Restart service httpd, in all cases
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes

- name: Download HTDOCS Under Nginx Path 
  get_url:
    url: "https://github.com/roboshop-devops-project/frontend/archive/main.zip"
    dest: /tmp/main.zip 
    mode: '0777'
- name: Unarchive a file that needs to be downloaded (added in 2.0)
  ansible.builtin.unarchive:
    src: https://example.com/example.zip
    dest: /usr/local/bin
    remote_src: yes