- name: Install the latest version of Ngnix 
  yum:
    name: nginx 
    state: latest
  tags:
    - frontend 

- name: Downloading {{ APP }} component 


- name: Restart service httpd, in all cases
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes

- name: remove the old content 
  ansible.builtin.shell: rm -rf /usr/share/nginx/html/

- name: Download and Unarchive the Zip  
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/frontend/archive/main.zip
    dest: /usr/share/nginx/html
  remote_src: yes