- name: Install the latest version of Ngnix 
  yum:
    name: nginx 
    state: latest
  tags:
    - frontend 

- name: Restart service httpd, in all cases
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes

- name: Download HTDOCS Under Nginx Path 
  get_url:
    url: ""
    dest: /tmp/main.zip 
    mode: '0777'

- name: Execute the command in remote shell; stdout goes to the specified file on the remote
  ansible.builtin.shell: somescript.sh >> somelog.txt

- name: Unarchive the zip 
  ansible.builtin.unarchive:
    src: https://github.com/roboshop-devops-project/frontend/archive/main.zip
    dest: /usr/share/nginx/html
    remote_src: yes