- name: Install the latest version of Ngnix 
  yum:
    name: nginx 
    state: latest

- name: Downloading {{ APP }} component 
  include_role:
    name: common
    tasks_from: curl_download 
  vars: 
    - URL: "https://github.com/roboshop-devops-project/frontend/archive/main.zip"
    - EXTRACT_DIR: "/usr/share/nginx/html"

- name: Execute the command in remote shell; stdout goes to the specified file on the remote
  ansible.builtin.shell: somescript.sh >> somelog.txt

- name: Restart service {{ APP }} 
  ansible.builtin.service:
    name: nginx 
    state: restarted




