- name: Install the latest version of Ngnix 
  yum:
    name: nginx 
    state: latest
  tags:
    - frontend 

- name: Downloading {{ APP }} component 
  include_role:
    name: common
    tasks_from: curl_download 
  vars: 
    - URL: "https://github.com/roboshop-devops-project/frontend/archive/main.zip"
    - EXTRACT_DIR: "/usr/share/nginx/html"

- name: Restart service httpd, in all cases
  ansible.builtin.service:
    name: nginx
    state: restarted
    enabled: yes

- name: remove the old content 
  ansible.builtin.shell: rm -rf /usr/share/nginx/html/

