- name: Install the latest version of Ngnix 
  yum:
    name: nginx 
    state: latest

- name: Downloading {{ APP }} component 
  include_role:
    name: common
    tasks_from: curl_download 
  vars: 
 #   - URL: "http://172.31.77.55:8081/repository/frontend/frontend.1.{{ APP_VERSION }}.zip"
    - URL: "https://github.com/roboshop-devops-project/frontend/archive/main.zip"
    - EXTRACT_DIR: "/usr/share/nginx/html"

- name: Updating the Proxy 
  ansible.builtin.template:
    src: roboshop.conf 
    dest: /etc/nginx/default.d/roboshop.conf

- name: Restart service {{ APP }} 
  ansible.builtin.service:
    name: nginx 
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Setup the Prometheus Node_exporter 
  iinclude_role:
  