
- name: Installing catalog PreReq Packages
  yum:
    name:
      - nodejs 
      - make 
      - gcc-c++ 
    state: present
  
- name: Creating roboshop user
  ansible.builtin.user:
    name: roboshop


