
- name: Installing catalog PreReq Packages
  yum:
    name:
      - nodejs 
      - make 
      - gcc-c++ 
    state: present
  
- name: Downloading {{ APP }} component 
  include_role:
    name: common
    tasks_from: curl_download 
  vars: 
    - URL: "https://github.com/roboshop-devops-project/catalogue/archive/main.zip"
    - EXTRACT_DIR: "/home/roboshop/catalogue" 

- name: Installing nodeJS App 
  community.general.npm:
    name: coffee-script
    path: "{{ EXTRACT_DIR }}"



