
- name: Installing catalog Redis Packages
  ansible.builtin.yum:
     name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
     state: present

- name: Install Redis
  ansible.builtin.yum:
    name: redis
    state: present
    enablerepo: "remi"



- name: Start Catalogue
  ansible.builtin.systemd:
    name: redis 
    state: restarted
    enabled: yes
    daemon_reload: yes

