
- name: Installing catalog Redis Packages
  ansible.builtin.yum:
     name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
     state: present
     enablerepo: remi

- name: Start Redis
  ansible.builtin.yum:
     name: http://rpms.remirepo.net/enterprise/remi-release-7.rpm
     state: present
     enablerepo: remi
