- name: Install Maven 
  yum:
    name: maven
    state: latest

- name: Downloading Shipping Code  
  include_role:
    name: common
    tasks_from: curl_download 
  vars: 
    - URL: "https://github.com/roboshop-devops-project/shipping/archive/main.zip"
    - EXTRACT_DIR: "/home/roboshop/shipping" 
    - APP_USER: "roboshop"

- name: Install Maven Modules
  ansible.builtin.shell: mvn clean package && mv target/shipping-1.0.jar shipping.jar
  args:
    chdir: /home/roboshop/{{ APP }}/

  become_user: roboshop

- name: Updating cartEndPoint in Shipping config file 
  ansible.builtin.replace:
    path:  /home/roboshop/shipping/systemd.service
    regexp: 'CARTENDPOINT'
    replace: "cart-{{ ENV }}.manojtestdmn.tk"
  
- name: Placing cart svc in etc system 
  shell: cp /home/roboshop/shipping/systemd.service /etc/systemd/system/shipping.service

- name: Start shipping 
  ansible.builtin.systemd:
    name: shipping  
    state: restarted
    enabled: yes
    daemon_reload: yes