- name: Install Maven 
  yum:
    name: maven
    state: latest

- name: Downloading Shipping Code  
  include_role:
    name: common
    tasks_from: curl_download 
  vars: 
    - URL: "https://github.com/roboshop-devops-project/shipping/archive/main.zip"
    - EXTRACT_DIR: "/home/roboshop/shipping" 
    - APP_USER: "roboshop"

- name: Install Maven Modules
  ansible.builtin.shell: mvn clean package && mv target/shipping-1.0.jar shipping.jar
  args:
    chdir: /home/roboshop/{{ APP }}/
  become_user: roboshop


- name: Update Redis configuration file from Listening on 127.0.0.1 to 0.0.0.0
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Start Redis 
  ansible.builtin.systemd:
    name: redis 
    state: restarted
    enabled: yes
    daemon_reload: yes
