- name: Copy MySQL repo
  ansible.builtin.copy:
    src: mysql.repo 
    dest: /etc/yum.repos.d/mysql.repo

- name: Remove mariadb-libs 
  yum:
    name: mariadb-libs
    state: absent

- name: Install mariadb-libs 
  yum:
    name: mariadb-libs
    state: absent
  