- name: Copy MySQL repo
  ansible.builtin.copy:
    src: mysql.repo 
    dest: /etc/yum.repos.d/mysql.repo

- name: Remove mariadb-libs 
  yum:
    name: mariadb-libs
    state: absent

- name: Install MySQL
  yum:
    name: mysql-community-server
    state: present 

- name: Start MySQL 
  ansible.builtin.systemd:
    name: mysqld 
    state: restarted
    enabled: yes
    daemon_reload: yes

- name: Check DB has been configured or not
  shell: echo "show databases;" | mysql -uroot -ppassword
  ignore_errors: yes
  register: out

- name: Print the status
  debug:
     msg: "{{ out }}"


- name: Reset Default Password
  when: out.rc != 0
  block: 
    - name: Get Default password 
      ansible.builtin.shell: grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}'
      register: PASSWORD 

    - name: Reset MySQL Password
      shell: mysql -uroot -p"{{PASSWORD.stdout}}" < /tmp/password.sql
    

- name: Get Default password 
  ansible.builtin.shell: grep 'temporary password' /var/log/mysqld.log | awk '{print $NF}'
  register: OUT 

- name: Print the password
  debug:
     msg: "{{ OUT.stdout_lines }}" 

