- name: Copy mongoDb repo
  ansible.builtin.copy:
    src: mongodb.repo 
    dest: /etc/yum.repos.d/mongodb.repo
  
- name: Install MongoDB 
  yum:
    name: mongodb-org 
    state: latest

- name: Restart  {{ APP }} service
  ansible.builtin.service:
    name: mongod 
    state: restarted

- name: Updating MongoDB config file 
  ansible.builtin.replace:
    path: /etc/hosts
    regexp: '(\s+)old\.host\.name(\s+.*)?$'
    replace: '\1new.host.name\2'