- name: Copy mongoDb repo
  ansible.builtin.copy:
    src: mongodb.repo 
    dest: /etc/yum.repos.d/mongodb.repo
  
- name: Install MongoDB 
  yum:
    name: mongodb-org 
    state: latest

- name: Updating MongoDB config file 
  ansible.builtin.replace:
    path:  /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: Restart  {{ APP }} service
  ansible.builtin.service:
    name: mongod 
    state: restarted

- name: Downloading {{ APP }} schema  
  include_role:
    name: common
    tasks_from: curl_download 
  vars: 
    - URL: "https://github.com/roboshop-devops-project/mongodb/archive/main.zip"
    - EXTRACT_DIR: "/tmp"

- name: Loading Mongo Schema 
  ansible.builtin.shell: somescript.sh >> somelog.txt
  args:
    chdir: /tmp/mongodb-main

