
- name: Copy mongoDb repo
  ansible.builtin.copy:
    src: mongodb.repo 
    dest: /etc/yum.repos.d/mongodb.repo
  
- name: Install the latest version of Apache
  yum:
    name: httpd
    state: latest