- name: Install Filebeat
  yum:
    name: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.12.1-x86_64.rpm
    state: installed

- name: Copy Filebeat Configuration
  template:
    src: filebeat.yml
    dest: /etc/filebeat/filebeat.yml

- name: Start Filebeat Service
  systemd:
    name: filebeat
    state: restarted
    enabled: yes

