- name: Installing cart PreRequisite Packages
  yum:
    name:
      - nodejs 
      - make 
      - gcc-c++ 
    state: present

- name: Downloading cart  component 
  include_role:
    name: common
    tasks_from: curl_download 
  vars: 
    - URL: "https://github.com/roboshop-devops-project/cart/archive/main.zip"
    - EXTRACT_DIR: "/home/roboshop/cart" 
    - APP_USER: "roboshop"

- name: Installing nodeJS modules 
  community.general.npm:
    path: "{{ EXTRACT_DIR }}"
  become_user: roboshop 
  vars: 
    - EXTRACT_DIR: "/home/roboshop/cart" 

- name: Updating redis in user config file 
  ansible.builtin.replace:
    path:  /home/roboshop/cart/systemd.service
    regexp: 'REDIS_ENDPOINT'
    replace: "redis-{{ ENV }}.manojtestdmn.tk"
  
- name: Updating mongo in user config file 
  ansible.builtin.replace:
    path:  /home/roboshop/user/systemd.service
    regexp: 'MONGO_ENDPOINT'
    replace: "mongodb-{{ ENV }}.manojtestdmn.tk"

- name: Placing user in etc system 
  shell: cp /home/roboshop/user/systemd.service /etc/systemd/system/user.service

- name: Start User 
  ansible.builtin.systemd:
    name: user  
    state: restarted
    enabled: yes
    daemon_reload: yes
