filebeat.inputs:
{% if APP == 'catalogue' or APP == 'cart' or APP == 'user' %}
  - type: log
    enabled: true
    paths:
      - /var/log/{{APP}}.log
    json.keys_under_root: true
    json.message_key: msg
{% elif APP == 'frontend' %}
  - type: log
    enabled: true
    paths:
      - /var/log/nginx/access.log
    fields:
      log_type: nginx_access
  - type: log
    enabled: true
    paths:
      - /var/log/nginx/error.log
    fields:
      log_type: nginx_error
{% elif APP == 'payment' %}
  - type: log
    enabled: true
    paths:
      - /var/log/{{APP}}.log
    json.keys_under_root: true
    json.message_key: msg
    fields:
      log_type: {{APP}}
    include_lines: ['^\[[0-9][0-9][0-9][0-9]']
{% elif APP == 'shipping' %}
  - type: log
    enabled: true
    paths:
      - /var/log/{{APP}}.log
    fields:
      log_type: {{APP}}
    include_lines: ["^[0-9][0-9][0-9][0-9]"]
{%endif%}

filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
setup.template.settings:
  index.number_of_shards: 1
setup.kibana:

{% if APP == 'catalogue' or APP == 'cart' or APP == 'user' %}
output.elasticsearch:
  hosts: ["172.31.59.150:9200"]
  index: "{{APP}}-%{+yyyy.MM.dd}"
setup.template.name: "{{APP}}"
setup.template.pattern: "{{APP}}-*"
setup.template.enabled: false
setup.ilm.enabled: false
{% elif APP == 'frontend' or APP == 'shipping' or APP == 'payment' %}
output.logstash:
  hosts: ["172.31.59.150:5044"]
{%endif%}