- name: Installing Python3
  yum:
    name:
      - python36 
      - gcc  
      - python3-devel
    state: present

- name: Downloading Payment Code 
  include_role:
    name: common
    tasks_from: curl_download 
  vars: 
    - URL: "https://github.com/roboshop-devops-project/payment/archive/main.zip"
    - EXTRACT_DIR: "/home/roboshop/payment" 
    - APP_USER: "roboshop"

- name: Installing Dependencies   
  pip:
    requirements: /home/roboshop/payment/requirements.txt
    executable: pip3

- name: Fetching the uid roboshop user 
  shell: id roboshop -u
  register: RUID

- name: Fetching the uid roboshop user 
  shell: id roboshop -u
  register: RUID

- name: Updating the uid 
  ansible.builtin.lineinfile:
    path: /home/roboshop/payment/payment.ini
    regexp: '^uid'
    line: uid={{ ruid }}

- name: Updating the gid 
  ansible.builtin.lineinfile:
    path: /home/roboshop/payment/payment.ini
    regexp: '^gid'
    line: gid={{ rgid }}

- name: systemd copy
  ansible.builtin.template:
    src: systemd.service 
    dest: /etc/systemd/system/payment.service

- name: Start Payment 
  ansible.builtin.systemd:
    name: payment 
    state: restarted
    enabled: yes
    daemon_reload: yes