- name: Installing Python3
  yum:
    name:
      - python36 
      - gcc  
      - python3-devel
    state: present

- name: Downloading Payment Code 
  include_role:
    name: common
    tasks_from: curl_download 
  vars: 
    - URL: "https://github.com/roboshop-devops-project/payment/archive/main.zip"
    - EXTRACT_DIR: "/home/roboshop/payment" 
    - APP_USER: "roboshop"

- name: Installing Dependencies   
  pip:
    requirements: /home/roboshop/payment/requirements.txt
    executable: pip3

- name: Fetching the uid and gid of roboshop user 
  shell: UID=$(id roboshop -u) && GID=$(id roboshop -g)