- name: Installing Python3
  yum:
    name:
      - python36 
      - gcc  
      - python3-devel
    state: present

- name: Downloading cart  component 
  include_role:
    name: common
    tasks_from: curl_download 
  vars: 
    - URL: "https://github.com/roboshop-devops-project/payment/archive/main.zip"
    - EXTRACT_DIR: "/home/roboshop/cart" 
    - APP_USER: "roboshop"