- name: Downloading {{ APP }} Component 
  get_url:
    url: "{{ URL }}"
    dest: /tmp/{{ APP }}.zip 

- name: remove the old content
  ansible.builtin.file:
    path: "{{ EXTRACT_DIR }}"
    state: absent

- name: create the {{ APP }} dir 
  ansible.builtin.file:
    path: "{{ EXTRACT_DIR }}"
    state: directory  

- name: Download and Unarchive the Zip  
  ansible.builtin.unarchive:
    src: /tmp/{{ APP }}.zip 
    dest: "{{ EXTRACT_DIR }}"
    remote_src: yesbecome_user: "{{APP_USER}}"

- name: Execute the command in remote shell; stdout goes to the specified file on the remote
  ansible.builtin.shell: mv /usr/share/nginx/html/frontend-main/* . ; 

