
- name: remove the old content
  ansible.builtin.file:
    path: "{{ EXTRACT_DIR }}"
    state: absent
  ignore_errors: yes 

- name: create the {{ APP }} dir 
  ansible.builtin.file:
    path: "{{ EXTRACT_DIR }}"
    state: directory  

- name: Downloading THE {{ APP }} Component 
  ansible.builtin.get_url:
    url: "{{ URL }}"
    dest: /tmp/{{ APP }}.zip 
    url_username: admin
    url_password: "{{ NEXUS_PWD }}"
  vars:
     URL: "http://172.31.77.55:8081/repository/frontend/frontend.1.{{ APP_VERSION }}.zip"


- name: Download and Unarchive the Zip  
  ansible.builtin.unarchive:
    src: /tmp/{{ APP }}.zip 
    dest: "{{ EXTRACT_DIR }}"
    remote_src: yes 

# - name: Move Components Directory
#   shell: mv {{ EXTRACT_DIR }}/{{ APP }}-main {{ EXTRACT_DIR }}/{{ APP }}
#   ignore_errors: yes 

- name: Moving things to back
  shell: mv /home/roboshop/{{ APP}}/{{ APP }}/* /home/roboshop/{{ APP }}/  && rm -rf /home/roboshop/catalogue/catalogue
  when: APP == "catalogue" or  APP == "user" or  APP == "cart" or  APP == "shipping" or  APP == "payment"

- name: Changing Ownership
  ansible.builtin.file:
    path: "{{ EXTRACT_DIR }}"
    owner: roboshop
    group: roboshop 
    state: directory
    recurse: yes
  when: APP == "catalogue" or  APP == "user" or  APP == "cart" or  APP == "shipping" or  APP == "payment"

# Disable this when Downloading from NEXUS
- name: Move HTDOCS Directory 
  shell: mv "{{ EXTRACT_DIR }}/frontend/* /usr/share/nginx/html/." &&  mv "{{ EXTRACT_DIR }}"/static/*  "{{ EXTRACT_DIR }}"/. && rm -rf "{{ EXTRACT_DIR }}"/frontend-master "{{ EXTRACT_DIR }}"/README.md && mv "{{ EXTRACT_DIR }}"/localhost.conf /etc/nginx/default.d/roboshop.conf
  when: APP == "frontend" 