- name: Get node_exporter directory is there or not
  ansible.builtin.stat:
    path: /opt/node_exporget
  register: sym

- name: Grep the node_expirter version  
  shell: "curl -s https://github.com/prometheus/node_exporter/releases | grep css-truncate-target | grep '<span class'  | head -1 | sed s/\</\ /g |sed s/\>/\ /g  | xargs | awk '{print $(NF-1)}'