- name: Install NodeJS
  yum:
    name:
      - nodejs
      - make
      - gcc-c++
    state: present
  
- name: Install NodeJS Modules
  npm:
    path: /home/roboshop/{{COMPONENT}}
  become_user: roboshop